#!/bin/bash

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# vim
if [ ! -f ~/.vimrc ]; then
	ln -s ${BASE}/vim/vimrc ~/.vimrc 
fi

# zsh
if [ ! -f ~/.zshrc ]; then
	ln -s ${BASE}/zsh/zshrc ~/.zshrc
fi
if [ ! -f ~/.zshrc ]; then
	ln -s ${BASE}/zsh/zprofile ~/.zprofile
fi

# git
if [ ! -f ~/.gitconfig ]; then
	ln -s ${BASE}/git/gitconfig ~/.gitconfig
fi

# Xorg
if [ ! -f ~/.xinitrc ]; then
	ln -s ${BASE}/xorg/xinitrc ~/.xinitrc
fi

# others
