theme = "springan"

[editor]
line-number = "relative"
scrolloff = 8
mouse = false
cursorline = true
cursorcolumn = true
color-modes = true
bufferline = "always"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "version-control"]
center = ["file-name"]
right = ["workspace-diagnostics", "file-type", "selections", "position", "file-encoding"]
separator = "│"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "all"

[editor.whitespace.characters]
newline = "󱞥"

[editor.indent-guides]
render = true
character = "│"

# keymaps
[keys.normal]
X = "extend_line_above"
