theme = "springan"

[editor]
line-number = "relative"
scrolloff = 8
mouse = true
cursorline = true
color-modes = true
# bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "file-type", "selections", "position", "file-encoding"]
separator = "│"

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "all"

[editor.whitespace.characters]
newline = ""

[editor.indent-guides]
render = true
character = "│"

# keymaps
[keys.normal]
X = "extend_line_above"
A-y = [ "extend_line_below", "yank" ]
A-d = [ "extend_line_below", "delete_selection" ]