" Consistency settings
set nocompatible
"set tabstop=4
"set shiftwidth=4
"set expandtab

" Functionality settings
set incsearch
set hlsearch
filetype plugin indent on

" Display/look related settings
syntax on
set number

" Netrw settings
let g:netrw_banner = 0 		" disable hideous banner
let g:netrw_liststyle = 3	" select default layout
let g:netrw_browse_split = 4	" mimic file openning from IDEs
let g:netrw_winsize = 25	" width of explorer set to 25%
let g:netrw_altv = 1		" puts netrw to the left

" Alias for vim commands
command Vex Vexplore

