#!/usr/bin/env sh

power_off='󰐥'
reboot='󰜉'
lock='󰌾'
suspend='󰒲'

rofi_prompt() {
  yes='Confirm'
  no='Cancel'
  query='Are you sure?'

  while [ $# -ne 0 ]; do
    case "$1" in
      -y | --yes)
        [ -n "$2" ] && yes="$2" || yes=''
        shift
        ;;

      -n | --no)
        [ -n "$2" ] && no="$2" || no=''
        shift
        ;;

      -q | --query)
        [ -n "$2" ] && query="$2"
        shift
        ;;
    esac
    shift
  done

  chosen=$(printf '%s;%s\n' "$yes" "$no" \
    | rofi -theme-str '@import "prompt.rasi"' \
         -p "$query" \
         -dmenu \
         -sep ';' \
         -a 0 \
         -u 1 \
         -selected-row 1)

  case "$chosen" in
    "$yes") exit 0 ;;
    *)      exit 1 ;;
  esac
}

chosen=$(printf '%s;%s;%s;%s' "$lock" "$reboot" "$power_off" "$suspend" \
    | rofi -theme-str '@import "power.rasi"' \
        -dmenu \
        -sep ';' \
        -selected-row 2)

case "$chosen" in
    "$power_off")
        # rofi_prompt --query 'Shutdown?' && poweroff
        notify-send 'Shutdown? no prompt' && sleep 1 && poweroff
        ;;

    "$reboot")
        # rofi_prompt --query 'Reboot?' && reboot
        notify-send 'Reboot? no prompt' && sleep 1 && reboot
        ;;

    "$lock")
        notify-send 'No lock yet'
        ;;

    "$suspend")
        notify-send 'No lock yet'
        ;;

    *) exit 1 ;;
esac

