#!/bin/bash

set_bg() {
	wall=".local/share/wallpapers/forest_sunset_wpf.jpg"

	# kill all other compositor instances
	killall -q picom

	# Start compositor and background
	feh --bg-scale $wall -V && python -m pywal -i $wall &
	if [ "$1" == "-c" ]
	then
		picom
        fi	
	#&& python -m pywal  -i $bg
}

set_bg $1

