#!/bin/bash

set_bg() {
	wall=".local/share/wallpapers/forest_mountain_birds_wpf.png"

	# kill all other compositor instances
	killall -q picom

	while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

	# Start compositor and background
	feh --bg-scale $wall -V && python -m pywal -i $wall &
	if [ "$1" == "-c" ]
	then
		picom --experimental-backends & 
        fi	
}

set_bg $1

