#!/bin/bash

usage() {
  cat <<EOF
Usage:
  notify [options ...] <title> <description>

Send a notification using a supported utility, such as 'libnotify' (default).

Options:
  -h, --help                Display this message and exit
  -l, --list-backends       Lists all supported backends, such as 'libnotify'  
  -b, --backend <backend>   Specify the backend to use (from the list of supported ones)
  -i, --icon <file>         Icon to show in the notification (<file> can be a path, name etc.)
  -a, --audio <file>        Audio clip to play with the notification (<file> can be a path, name etc.)

Examples:
  notify 'Hello' 'World!'
EOF
}

supported_backends() {
  cat <<EOF
Supported Backends:
  libnotify   Library for sending desktop notifications.
              https://developer.gnome.org/notification-spec/
EOF
}

error() {
  cat <<EOF
[ERROR] notify: $1
Try 'notify --help' for more information.
EOF
  exit 1
}

assign_parameter_value() {
  if [ "$backend" == "-1" ]; then
    backend=$1
  elif [ "$icon" == "-1" ]; then
    icon=$1
  elif [ "$audio" == "-1" ]; then
    audio=$1
  elif ! [ -n "$title" ]; then
    title="$1"
  else
    if [ -n "$description" ]; then
      description="$description"
    fi
    description="$1"
  fi
}

validate_parameters() {
  if ! [ -n "$title" ]; then
    error "Missing <title> from the received parameters."
  fi

  if [ "$backend" == "-1" ]; then
    error "Missing <backend> required by the '-b/--backend' flag."
  fi

  if [ "$icon" == "-1" ]; then
    error "Missing <file> required by the '-i/--icon' flag."
  fi

  if [ "$audio" == "-1" ]; then
    error "Missing <file> required by the '-a/--audio' flag."
  fi
}

send_libnotify() {
  action="notify-send \"$1\" \"$2\""

  if [ -n "$icon" ]; then
    action="$action -i $icon"
  fi
}

send_notification() {
  case $backend in
    libnotify)
      if ! [ -x "$(command -v notify-send)" ]; then
        echo "[FATAL] notify: Failed to find 'libnotify'."
        echo "Try 'notify --list-backends' for the list of supported backends."
        exit 1
      fi
      send_libnotify "$1" "$2"
    ;;
    *)
      echo "[FATAL] notify: Backend '$1' not supported."
      echo "Try 'notify --list-backends' for the list of supported backends."
      exit 1
    ;;
  esac

  if [ -n "$audio" ]; then
    if [ -x "$(command -v paplay)" ]; then
      play_audio="paplay $audio"
    elif [ -x "$(command -v aplay)" ]; then
      play_audio="aplay $audio"
    fi

    if ! [ -n "$play_audio" ]; then
      echo "[WARN] notify: Could not detect either ALSA or PluseAudio for playing sounds."
      exit 1
    fi

    action="$action && $play_audio"
  fi

  exec sh -c "$action"
}

main() {
  if [ $# -lt "1" ]; then
    usage
    exit 0
  fi

  backend="libnotify"
  title=""
  description=""

  for i in "$@"
  do
    case $i in
      -h | --help)
        usage
        exit 0
      ;;
      -l | --list-backends)
        supported_backends
        exit 0
      ;;
      -b | --backend)
        backend=-1
      ;;
      -i | --icon)
        icon=-1
      ;;
      -a | --audio)
        audio=-1
      ;;
      -*)
        cat <<EOF
[ERROR] notify: invalid option -- '$i'
Try 'notify --help' for more information.
EOF
        exit 1
      ;;
      *)
        assign_parameter_value "$i"
      ;;
    esac
  done

  validate_parameters
  send_notification "$title" "$description"

  exit 0
}

main "$@"
