#!/bin/bash

# Kill all previous instances
killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

echo "------" | tee -a /tmp/polybar.log
#polybar main >>/tmp/polybar.log 2>&1 &
polybar main_nogaps >>/tmp/polybar.log 2>&1 &
#echo "------" | tee -a /tmp/polybar-workspaces.log /tmp/polybar-system.log
#polybar workspaces >>/tmp/polybar-workspaces.log 2>&1 &
#polybar system >>/tmp/polybar-system.log 2>&1 &

echo "Launched Polybar"

