#!/bin/bash

# Kill all previous instances
killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

echo "------" | tee -a /tmp/polybar.log
polybar example >>/tmp/polybar.log 2>&1 &

echo "Launched Polybar"

