# Lines configured by zsh-newuser-install
#HISTFILE=${DOTFILES}/zsh/histfile
#HISTSIZE=1000
#SAVEHIST=1000
setopt autocd nomatch
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '${DOTFILES}/.zshrc'

autoload -Uz compinit
compinit -d ${DOTFILES}/.cache/zsh/zcompdump-${ZSH_VERSION}
# End of lines added by compinstall

# set plugins
plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
)

# ZSH Correct typos
setopt correct

# Set PS1
autoload -U colors && colors
# Set Colors
(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh
#PS1="%F{magenta}[%F{green}%n%F{magenta}@%m %F{cyan}%~%F{magenta}]%F{cyan}\$%F{white} "
PROMPT="%F{red}%n %F{cyan}%~ %F{green}>> %F{white}"


# Keymap settings
bindkey -v	# Use VIM style
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char

# Aliases
alias szsh="source ${HOME}/.zshrc"
alias ls="ls --color=auto"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias gitps="git push"

# Other "aliases" (functions)
# Git add, commit and push all files in current directory
gitcp() {   
	if [ -n "$1" ]
       	then
		git add . && git commit -m "$1" && git push
	else
		echo "Error: Cannot push without a commit message."
	fi
}

# Git add all files in current directory and commit
gitc() {    
	if [ -n "$1" ]
       	then
		git add . && git commit -m "$1"
	else
		echo "Error: Cannot push without a commit message."
	fi
}

# Change wallpaper and colour schemes/backgrounds based on it
chbg() {
	if [[ -f $1 ]]
       	then
		feh --bg-scale $1 && python -m pywal  -i $1
	else
		echo "Error: Cannot change background without a picture."
	fi
}

# ZSH Syntax Highlighting source
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

