# Lines configured by zsh-newuser-install
HISTFILE=${DOTFILES}/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd nomatch
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '${DOTFILES}/.zshrc'

autoload -Uz compinit
compinit -d ${DOTFILES}/.cache/zsh/zcompdump-${ZSH_VERSION}
# End of lines added by compinstall

# set plugins
plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
)

# ZSH Correct typos
setopt correct

# Add "bin" folder to PATH (like in bash)
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Set PS1
autoload -U colors && colors
#PS1="%F{magenta}[%F{green}%n%F{magenta}@%m %F{cyan}%~%F{magenta}]%F{cyan}\$%F{white} "
PS1="%F{magenta}[%F{green}%n%F{magenta}@%m %F{cyan}%~%F{magenta}]%F{cyan}\$%F{white} "


# Keymap settings
bindkey -v	# Use VIM style

# Aliases
alias szsh="source ${HOME}/.zshrc"
alias ls="ls --color=auto"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias gitp="git push"

# Other "aliases" (functions)
gitcp() {   # Git add, commit and push all files in current directory
	if [ -n "$1" ]; then
		git add . && git commit -m "$!" && git push
	else
		echo "Error: Cannot push without a commit message."
	fi
}

gitc() {    # Git add all files in current directory and commit
	if [ -n "$1" ]; then
		git add . && git commit -m "$!"
	else
		echo "Error: Cannot push without a commit message."
	fi
}

# ZSH Syntax Highlighting source
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
